server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ridelink_ride_db

driver-service:
  base-url: http://localhost:8082

jwt:
  secret: ${JWT_SECRET:83f510be14120fdb4a4d952675b34ebcfef016a50da3e30f36798c92a95c4cfc}
