server.port=8083
spring.data.mongodb.uri=mongodb+srv://uvindushehansampath_db_user:Uvindu2004@cluster0.y1ou8rt.mongodb.net/ridelink_ride_db?appName=Cluster0

driver-service.base-url=http://localhost:8082


jwt.secret=${JWT_SECRET:83f510be14120fdb4a4d952675b34ebcfef016a50da3e30f36798c92a95c4cfc}
