server:
  port: 8081

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_service_db
      auto-index-creation: true

# SpringDoc / Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
